# Generated by Django 4.1.3 on 2022-11-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('q_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('q_file', models.FileField(blank=True, null=True, upload_to='')),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('BT_level', models.IntegerField(blank=True, null=True)),
                ('max_marks', models.IntegerField(blank=True, null=True)),
                ('upvotes', models.IntegerField(blank=True, null=True)),
                ('flag_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('topics', models.ManyToManyField(to='api.questions')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('topics', models.ManyToManyField(to='api.topics')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('modules', models.ManyToManyField(to='api.module')),
            ],
        ),
    ]
