# Generated by Django 4.1.3 on 2022-11-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_courses_modules_alter_module_topics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='topics',
            new_name='questions',
        ),
    ]
