# Generated by Django 4.1.3 on 2022-11-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_topics_topics_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='courses',
            name='modules',
            field=models.ManyToManyField(to='api.module'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
