# Generated by Django 4.1.3 on 2022-11-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_questions_has_bookmarked_questions_has_upvoted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upvote_check',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
