# Generated by Django 4.1.3 on 2022-11-16 15:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_bookmarks_user_id_alter_upvote_check_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='flag_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('question_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='has_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
