# Generated by Django 4.1.3 on 2022-11-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_flag_check_questions_has_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='modules',
            field=models.ManyToManyField(blank=True, null=True, to='api.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='api.topics'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='api.questions'),
        ),
    ]
