# Generated by Django 4.1.3 on 2022-11-17 04:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_courses_modules_alter_module_topics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_mcq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, null=True, size=None)),
                ('correct_option', models.CharField(blank=True, max_length=500, null=True)),
                ('more_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, null=True, size=None)),
            ],
        ),
    ]
