# Generated by Django 4.1.5 on 2023-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_questions_q_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q_file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
