# Generated by Django 4.1.3 on 2022-11-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_courses_code_alter_courses_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='topics',
            field=models.ManyToManyField(to='api.topics'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topics',
            name='questions',
            field=models.ManyToManyField(to='api.questions'),
        ),
    ]
