# Generated by Django 4.1.3 on 2022-11-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_module_name_alter_module_topics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('option_1', models.CharField(blank=True, max_length=500, null=True)),
                ('option_2', models.CharField(blank=True, max_length=500, null=True)),
                ('option_3', models.CharField(blank=True, max_length=500, null=True)),
                ('option_4', models.CharField(blank=True, max_length=500, null=True)),
                ('correct_option', models.IntegerField()),
            ],
        ),
    ]
