# Generated by Django 4.1.3 on 2022-11-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_questions_option_1_questions_option_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='correct_option',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
