# Generated by Django 4.1.3 on 2022-11-15 17:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='question_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='upvote_check',
            name='question_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
