# Generated by Django 4.1.3 on 2022-11-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_bookmarks_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='has_bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='has_upvoted',
            field=models.BooleanField(default=False),
        ),
    ]
