# Generated by Django 4.1.5 on 2023-01-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_temp_mcq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q_file',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
