# Generated by Django 4.1.2 on 2023-03-22 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=2000, null=True)),
                ('questionImage', models.CharField(blank=True, max_length=200, null=True)),
                ('questionFile', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('upvote_count', models.IntegerField(blank=True, default=0, null=True)),
                ('flag_count', models.IntegerField(blank=True, default=0, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.module')),
            ],
        ),
        migrations.CreateModel(
            name='Upvotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.post')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.post')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.post')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile')),
            ],
        ),
    ]
