# Generated by Django 4.1.2 on 2023-03-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bookmark_postid_alter_bookmark_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='BT_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
