# Generated by Django 4.1.2 on 2023-03-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_bt_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='questionImage',
        ),
    ]
