# Generated by Django 4.1.2 on 2023-03-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_post_questionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='marks',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
