# Generated by Django 4.1.2 on 2023-03-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='flag_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvote_count',
        ),
    ]
