# Generated by Django 4.1.2 on 2023-03-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_post_flag_count_remove_post_upvote_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='postID',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='flag',
            old_name='postID',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='flag',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='upvotes',
            old_name='postID',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='upvotes',
            old_name='userID',
            new_name='user',
        ),
    ]
