# Generated by Django 4.1.2 on 2023-03-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('accounts', '0002_userprofile_subjectincharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subjectInCharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.courses'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.IntegerField(default=0),
        ),
    ]
