# Generated by Django 4.1.2 on 2023-03-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('accounts', '0003_alter_userprofile_subjectincharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subjectInCharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses'),
        ),
    ]
