# Generated by Django 4.1.2 on 2023-03-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_subjectincharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.CharField(choices=[('1', 'Teacher'), ('2', 'Expert'), ('3', 'Superuser')], default='1', max_length=20),
        ),
    ]
