# Generated by Django 4.1.2 on 2023-03-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Expert', 'Expert')], default='Teacher', max_length=20),
        ),
    ]
