name: Ping model API every 36 hours

on:
  schedule:
    - cron: "0 */36 * * *"

jobs:
  ping_api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.9" # Replace with the version of Python you want to use
    - name: Install dependencies
      run: pip install -r requirements.txt # Replace with the name of your requirements file
    - name: Run Python script
      run: python ping_model.py # Replace with the name of your Python script
